### ISSUE TITLE
lineLengthForRow checking for existance

### ISSUE THREAD

**Issue by steelbrain** [atom/text-buffer#105]
Which results in https://github.com/AtomLinter/linter-pylint/issues/78
I've seen bug reports with the same trace in the past. The culprit is https://github.com/atom/text-buffer/blob/09935cd4c30d58cac3af24d35d46813b6b00faea/src/text-buffer.coffee#L504
Where you're just assuming that the line number exists, which in some cases isn't true.

**Comment by Arcanemagus** [comment]
This can be closed, the new (and completely different) implementation now lives over in `superstring` [here](https://github.com/atom/superstring/blob/master/src/bindings/text-buffer-wrapper.cc#L302-L311).
