### ISSUE TITLE
Sometimes tab inserts spaces, even with soft tabs off

### ISSUE THREAD

**Issue by chamons** [atom/text-buffer#11]
http://discuss.atom.io/t/sometimes-tab-inserts-spaces-even-with-soft-tabs-off/3976

**Comment by KevinMcCoy** [comment]
Problem still here why is this close?

**Comment by kosmonastya** [comment]
Same problem as @KevinMcCoy wrote

**Comment by Rinux55** [comment]
I also still have the problem. This makes Atom not usable for me.

**Comment by James-Firth** [comment]
This has also been causing a lot of issues with the team I'm on. I'm likely to switch back to Sublime now.

**Comment by MattWilcox** [comment]
Why is this marked as closed? This error persists.

**Comment by thomassross** [comment]
Hey guys,

A quick & easy fix is to install [auto-detect-indentation](https://atom.io/packages/auto-detect-indentation)

**Comment by benogle** [comment]
You folks can set these settings: 

![screen shot 2016-01-25 at 2 50 04 pm](https://cloud.githubusercontent.com/assets/69169/12567256/03f9fa44-c373-11e5-9b36-688ec87df94d.png)

`core.tabType` in config.cson

and

![screen shot 2016-01-25 at 2 50 11 pm](https://cloud.githubusercontent.com/assets/69169/12567259/08a8fa54-c373-11e5-9528-c127288cae31.png)

`core.softTabs` in config.cson

You can [scope them to languages](https://atom.io/docs/v1.4.1/using-atom-basic-customization#language-specific-settings-in-your-config-file) 

The auto-detection result will persist after manually replacing all tabs with another tab type. So if you replace them all, reload the file or set the `tabType` setting to the type you want.
