### ISSUE TITLE
Reloading doesn't effectly reload the file in the buffer

### ISSUE THREAD

**Issue by farvardin** [atom/text-buffer#124]
In Atom 1.3.2 (also in 1.0.2) and probably other versions as well, there is a "reload" option in the "View" menu. 

Expected behavior:

You have a text file opened in the buffer. Modify the file. Reload the file (ctrl + alt + r), there is a warning saying "File has changes, do you want to save them? Your changes will be lost if you close this item without saving.". After the reload, the file should be back to its initial state (the one saved on the disk).

Current behavior:

After the reload, the buffer is still in the modified state (with a blue dot indicating the buffer was changed). It hasn't reloaded at all. 

In addition, the warning message is not accurate: when we reload the tabs, we don't expect to "close this item" but to reload it.

**Comment by lee-dohm** [comment]
The "Reload" option in the View menu executes the `Window: Reload` command. This command is not intended to reload the file from disk, it is intended to reload the Atom environment mainly for developing packages.

If you want to reload the file from disk, you should close the file (saving or not saving the changes as desired) and then reopen it.

I agree though that the Reload menu item should probably be relocated to the Developer submenu and possibly be renamed to "Reload Window".
