### ISSUE TITLE
[QUESTION]: How can a plugin instantiate a `Point` ?

### ISSUE THREAD

**Issue by Byron** [atom/text-buffer#131]
Please apologize using the ticket system to ask a question - if there are better ways, I'd be glad to hear about them to use them in the future.

Even though points are returned by the API, I am having trouble finding the standard way of instantiating this type myself. I need to do this as part of my unit-tests for the [plugin](https://github.com/Byron/atom-byrons-edittools) I am writing.

Thank you

**Comment by mnquintana** [comment]
I might be misunderstanding, but you shouldn't need to instantiate a `Point` directly – any Atom methods that accept `Point`s also accept arrays of the coordinates, e.g. `[0, 140]`. Does that cover what you're looking for?

**Comment by Byron** [comment]
Thanks for getting back to me !
What I need is to use `Point` methods to aid my own computations. For this to work, I will want to instantiate points myself.

For example, [here](https://github.com/Byron/atom-byrons-edittools/blob/a0eb4a1f860717b831375c2b64754e67b57e690f/spec/integration/blocks/text.plain.coffee#L18) I set the cursor position, just to use that and [obtain a point at the given position](https://github.com/Byron/atom-byrons-edittools/blob/a0eb4a1f860717b831375c2b64754e67b57e690f/spec/integration/blocks/text.plain.coffee#L23) later. Doing that works but is more cumbersome than it has to be.

A viable solution could already be to use the constructor directly, such as in `new myPointInstance.constructor(0, 1)`. When looking at my code, I believe this is a viable way to do this.

Even though I am closing this ticket, it might be worth discussing whether utility types should provide a way to be instantiated from plugins as well.

**Comment by lee-dohm** [comment]
You should be able to get a hold of Atom's `Point` class by using (in CoffeeScript):

```
{Point} = require 'atom'
```

**Comment by Byron** [comment]
Thank you, this works perfectly.
It's interesting to know and finally understand that the `atom` instance is not to be confused with the `atom` module.
