### ISSUE TITLE
Painfully slow removal of trailing whitespace on save of large files

### ISSUE THREAD

**Issue by ArekSredzki** [atom/text-buffer#140]
## Problem description

If one tries to save a large file with atom, the save is performed asynchronously, and if it is configured to remove trailing whitespace, it will block the entire editor for a painfully long time.

Very often I will have a large JSON file open and out of the practice of good habit, I will regularly hit `meta-s` to save the file.  I will then be forced to take a stroll as the entire renderer window will be blocked for what is often a minute or so.

Today I finally performed a profile of the issue and nailed down the cause.
Here is the result for the reload of a _large_ file (~150,000 lines).
![Profiling Result](http://i.imgur.com/hH2fOPq.png)
## Suggested changes

Fix Regex
## Execution

I'll take a look at this tonight.

**Comment by lee-dohm** [comment]
I ran into this also with my [tabs-to-spaces package](https://atom.io/packages/tabs-to-spaces) which can do similar large-scale replacements on save, see https://github.com/lee-dohm/tabs-to-spaces/issues/16.

**Comment by ArekSredzki** [comment]
@lee-dohm I'll take that into account when I do a deep dive this evening, thanks for letting me know :+1:

**Comment by maxbrunsfeld** [comment]
This has been fixed: https://github.com/atom/whitespace/pull/140. The fix will ship in Atom 1.14.
