### ISSUE TITLE
[Feature Request] expose Patch or provide `getPatchFromCheckPoint(editor, checkpoint)` function. 

### ISSUE THREAD

**Issue by t9md** [atom/text-buffer#145]
I'm maintaining vim-mode-plus(forked version of vim-mode).
From text-buffer 8.4.1(which will be included in Atom 1.7+) it use Patch to manage buffer history.

In vim-mode-plus, I need to extract inserted text in `inser-mode` of vim-mode-plus to support "repeat last inserted text in insert-mode".
To achieve this, I need to extract newText from multiple changes from particular checkpoint.

This procedure is 

1. get history index for specified checkpoint
2. get undo stack from checkpoint
3. extract final newRange from multiple patch.

For last(3.) part,  this is exactly what `Patch.compose(patches)` is doing.
So I want to use `Patch.compose()` class method from my package or want text-buffer provide `getPatchFromCheckPoint(editor, checkpoint)` API which return composed patch from specified checkpoint.

Here I'm doing. Currently I get Patch class by consulting `patch.constrcutor`.

https://github.com/t9md/atom-vim-mode-plus/commit/aee6b93453127eedb009be3655a35e3dd12ea5f3

**Comment by as-cii** [comment]
So, I think we might expose a `TextBuffer.prototype.getChangesSinceCheckpoint(checkpointId)` method that returns a list of changes. Internally, we would use `Patch.compose` and combine intersecting changes, but for now I think it's better to be consistent with all the other change-related APIs, and not return a `Patch` object (I am also not totally opposed to it, as I can see usages of the `Patch` APIs that enable invertibility, composability, etc.).

@nathansobo: what do you think? Also, /cc: @BinaryMuse.

**Comment by nathansobo** [comment]
On board returning a list of changes.

**Comment by t9md** [comment]
:+1: Thanks for taking care of this request!
