### ISSUE TITLE
Don't always add second quote

### ISSUE THREAD

**Issue by Redsandro** [atom/text-buffer#148]
When starting with `'`, `"` or `, there appears a second quote after the cursor, which is expected and preferred.

When there's a selection, the second quote appears after the selection, which is also expected.

However, when a certain quote is selected and we type a quote because we want to replace it (e.g. double to single quote), we wrap the selection in quotes too. E.g. `"` -> `'"'`. This is not what we are trying to do. I propose when the selection holds a quote, one quote will replace the selection in stead of wrap the selection.

I'm new to Atom, and I couldn't find the code that does this.

**Comment by mnquintana** [comment]
Welcome to the Atom community! :tada: 

It sounds like you're looking for https://github.com/atom/bracket-matcher – would you mind doing a search for existing issues there, and then if you don't find anything, reopening this there? Thanks!

**Comment by Redsandro** [comment]
Thank you @mnquintana 
:leftwards_arrow_with_hook: https://github.com/atom/bracket-matcher/issues/227
