### ISSUE TITLE
Undo history grows without bound and slows down GC over time

### ISSUE THREAD

**Issue by nathansobo** [atom/text-buffer#15]
You can see the `History` instances are at the top of the dominators graph in this heap snapshot:

![screenshot 2014-04-07 15 06 40](https://cloud.githubusercontent.com/assets/1789/2637055/897194ac-be98-11e3-80a8-5b227828c88d.png)

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/atom/text-buffer/pull/97
