### ISSUE TITLE
Reloading window in dev mode no longer preserves undo history or scroll position

### ISSUE THREAD

**Issue by Alhadis** [atom/text-buffer#151]
Prior to v1.7.0, it was possible to undo changes to an opened document after reloading the window, as long as it'd been running in development mode. I always assumed this was a feature of dev mode: make changes to a package repo, reload window, see what's wrong, undo last change, repeat.

Since upgrading to v1.7.0, I'm no longer able to do this. I'm unsure if this is by design or just an honest bug (or even if the previous behaviour was a bug to begin with...)

**EDIT:** Also, the scroll offset isn't preserved after reloading the window: it reverts back to the top of the document. This wasn't the case before.

For the record, I'm using the *Reload window* command from the *View -> Developer* menu (which I've assigned the keyboard shortcut of <kbd>⌘ + shift + R</kbd>).

**Comment by 50Wliu** [comment]
@Alhadis I *think* this is an Atom core issue and not text-buffer; could you move this over there please?

**Comment by Alhadis** [comment]
Sorry... again. :(
