### ISSUE TITLE
Grammar overrides always case-sensitive

### ISSUE THREAD

**Issue by Alhadis** [atom/text-buffer#160]
Steps to reproduce:
1. Create a new file, and save it as "test.html"
2. Open [grammar-selector](https://github.com/atom/grammar-selector), and choose "Markdown"
3. Close file
4. Rename file "TEST.HTML"
5. Reopen: file's grammar will have reverted to HTML

I'm not sure if this is by design or an actual bug, but on case-insensitive filesystems (e.g., anything Unix-y), this probably isn't the expected behaviour.

**Comment by lee-dohm** [comment]
Aren't Unix filesystems typically case-sensitive by default? (macOS' HPFS+ being a notable exception.)

**Comment by Alhadis** [comment]
Whoops, I got that wrong... yeah, you're right, it's Mac OS that's case-insensitive (I'm running Mavericks). I always get that mixed up.

Either way, even on a case-sensitive filesystem, I'm sure a user who changes the capitalisation of a file would expect a file with the "same" name and extension to retain a user-assigned grammar.

**Comment by lee-dohm** [comment]
Cool, just making sure I understood :grinning:

**Comment by Alhadis** [comment]
Since grammar overrides now target `TextEditor` instances instead of file-paths, this is literally a non-issue (and it's been a non-issue for over a year now).
