### ISSUE TITLE
After update to 1.14.2 issues with opening large files

### ISSUE THREAD

**Issue by bferdinand** [atom/text-buffer#209]
Since the update to 1.14.2 I am not able to open larger files. Atom just hangs and then asks if I want to keep waiting, in an endless loop.

**Comment by maxbrunsfeld** [comment]
Can you give an example of a file for which performance has regressed?

**Comment by bferdinand** [comment]
I have uploaded a zip of the file and a screenshot of the popup I get after a while of waiting for it to unfreeze.
[file_causing_atom_crash.zip](https://github.com/atom/text-buffer/files/781000/file_causing_atom_crash.zip)

**Comment by maxbrunsfeld** [comment]
@bferdinand I see, it's a minified file. Did this file ever open quickly for you? I think Atom has always had problems opening these. I have good news though; we already merged a PR (https://github.com/atom/atom/pull/13820) that makes them open very quickly. This fix will be released in Atom 1.6.0, which will go into the March beta release.

**Comment by bferdinand** [comment]
Ok, yes they opened fine on 1.13.1. The syntax highlighting didn't always work perfectly, but it would load without a problem after about 5 - 10 seconds.

**Comment by bferdinand** [comment]
Also, was that a 1.6.0 release? or a 1.16 release?

**Comment by maxbrunsfeld** [comment]
I'm sorry, 1.16.

**Comment by maxbrunsfeld** [comment]
Ok, we've back-ported the fix that I mentioned above to the 1.15 beta branch. You can try v1.15.0-beta3 if you're interested.
