### ISSUE TITLE
text-buffer does not install on Windows

### ISSUE THREAD

**Issue by 50Wliu** [atom/text-buffer#219]
[This command](https://github.com/atom/text-buffer/blob/master/package.json#L10) expects the existence of `cp`.  `cp` does not exist using Window's `cmd.exe`.

```cmd
> coffee --no-header --output lib --compile src && cp src/*.js lib/

'cp' is not recognized as an internal or external command,
operable program or batch file.
```

(Edit: the slashes also need to be backslashes)

**Comment by pablorsk** [comment]
On windows, you need use `copy`. `cp` is for unix os.

Check powershell for windows (by Microsoft) and you don't problem like this anymore.

**Comment by 50Wliu** [comment]
Yes, I know that.  The problem is that the command I referenced in the package.json assumes Unix.

**Comment by pablorsk** [comment]
oh! sorry. I don't meet verywell `grunt` but with gulp I use a library. Maybe this library can be added to package.json and we can discard the use of `cp`:
https://www.npmjs.com/package/grunt-cp
