### ISSUE TITLE
Remove hard dependency on pathwatcher.File

### ISSUE THREAD

**Issue by bolinfest** [atom/text-buffer#23]
It would be great if the API of `pathwatcher.File` that `TextBuffer` needs could be abstracted out into its own interface, say `TextSource`. Then `TextBuffer` could depend on the `TextSource` interface, which could have multiple implementations. Obviously `pathwatcher.File` would implement `TextSource` by default, but it would also be possible to supply a `TextSource` for content that is not stored locally. (Obviously, async APIs would be preferred in that scenario.)

I would be happy to submit a patch for such a refactoring. Are there any examples of how to declare an interface in Atom?

**Comment by Alhadis** [comment]
> ... over three years later:

It's, uh, probably safe to close this now that we have a native buffer implementation, a formal filewatching API, and God-knows-how-many-other-changes have elapsed since this issue was filed... 😀
