### ISSUE TITLE
onDidStopChanging and undo Regression in Atom 1.19.4

### ISSUE THREAD

**Issue by GlenCFL** [atom/text-buffer#251]
With the recent update from Atom v1.19.3 to v1.19.4, the values passed to the callback which you provide to both TextEditor's onDidStopChanging and TextBuffer's onDidStopChanging have changed. I believe these Atom versions correlate with TextBuffer versions [v13.1.4 and v13.1.12](https://github.com/atom/text-buffer/compare/v13.1.4...v13.1.12), but I am not 100% sure due to Atom's documentation link for TextBuffer classes breaking with v1.19.

Text insertion continues to work as normal, so on editing a single line the callback provided to onDidStopChanging will be called with the following object:
```
{
  changes: TextChange[] = [
    {
      newExtent: Point (computed)
      newRange: Range
      newText: string
      oldExtent: Point (computed)
      oldRange: Range
      oldText: string
      start: Point (computed)
    }
  ]
}
```
However, if you were to undo that change within Atom, then you are now fed a changes array containing zero elements, whereas in Atom 1.19.3 this array would contain an instance of the TextChange class representing the change that undo has had on the buffer. This is causing buffer updating issues in a lot of Linter packages, with decorations just sticking around anytime a user uses undo after causing a Linter error.

This issue still exists in Atom 1.20.0-beta5 on both Windows x64 and Linux, with other platforms being untested.

**Comment by rsese** [comment]
Added to the project board for discussion but maybe /cc @maxbrunsfeld for 👓 on a potential regression?

**Comment by maxbrunsfeld** [comment]
Thanks for describing this in such detail @GlenCFL. My apologies for this very serious regression, I'll begin work on a fix tomorrow morning.

**Comment by dra1019** [comment]
I'm brand new to programming and getting started with all of this for an intro to programming class, this error popped up for me? Can someone tell me what to do to fix it? Thanks!

**Comment by maxbrunsfeld** [comment]
Upgrade to Atom 1.19.5.
