### ISSUE TITLE
existsSync method is necessary; should be reflected in comment

### ISSUE THREAD

**Issue by felzix** [atom/text-buffer#258]
https://github.com/atom/text-buffer/blob/4b6cbcd61356c1c0a01e04d6761648e1536a0a08/src/text-buffer.coffee#L598

If a file object is passed into `setFile` without having an `existsSync` method then an exception occurs due to [line 574](https://github.com/atom/text-buffer/blob/master/src/text-buffer.coffee#L574)

**Comment by maxbrunsfeld** [comment]
Good point! Want to open a PR adding that documentation?

**Comment by CaptainJohnyAppleSeed** [comment]
I agree, I wish that I'd realized that this was a necessary function. I'd be happy to submit a documentation PR.

**Comment by Arcanemagus** [comment]
Fixed in #293.
