### ISSUE TITLE
new TextBuffer(); .setFile(...); .reload();  -> .emitDidChangeEvent missing

### ISSUE THREAD

**Issue by ludwigkraatz** [atom/text-buffer#310]
I started using atom yesterday - today its time to try my first atom-package.
So i can only hope, i have everything figured out correctly so far..
[Atom: 1.35.1; OSX]

I'm trying to edit buffered content from some db - so no local-file accessible projects.

I have a test implementation of an Atom Package, opening a TextEditor using a buffer of a custom File-Object, which itself handles get/set of some db state.
Currently this is only triggered on [package].toggle() using a hardcoded test-uri.

On that toggle-event, i would expect a new TextEditor to open, with some hardcoded Text in it (DB_BufferedFile Mockup at Bottom of this Message).
What happens is, the editor window is opened, its file-name is correct, but no text is shown, as some kind of rerender of the editor is not triggered.

The workspace Opener, simply returning -new TextEditor(options)- for the hardcoded uri, works as expected.

in code, i would like the following to work [A]:
```javascript
const file = new DB_BufferFile(some_db_uri);

atom.workspace.open(some_db_uri, options).then(textEditor_item => {
        const buffer = textEditor_item.getBuffer(); // would be an empty buffer
        buffer.setFile(file);
        // the following line i actually do not want to use.. but would understand if i have to
        buffer.reload();
})
```
without the last line [A#L7|, the custom File is never read:
-DB_BufferedFile.createReadStream- is not called.
which seams to me.. experimental, like the comment suggests
https://github.com/atom/text-buffer/blob/master/src/text-buffer.js#L557

best case as i would like to use it [A*]:
```javascript
// reloads automatically and propagates change of complete content
buffer.setFile(file, {reload: true})
```

but i have to take this detour (at least it feals like a detour to me) [B]:
```javascript
const file = new DB_BufferFile(some_db_uri);

atom.workspace.open(some_db_uri, options).then(textEditor_item => {
        const buffer = textEditor_item.getBuffer();
        const changeEvent = {
          oldText: buffer.getText(),
          oldRange: buffer.getRange(),
        };

        buffer.setFile(file);
        buffer.reload().then(() =>  {
          changeEvent.newText = buffer.getText();
          changeEvent.newRange = buffer.getRange();
          buffer.emitDidChangeEvent(changeEvent)
        })
})
```
of course thats quite the dirty fix...
https://github.com/atom/text-buffer/blob/master/src/text-buffer.js#L907
TextBuffer's .applyChange() is far more than just the emitDidChangeEvent - but that solved my test - implementation - frustration at least for now.

Alternative implementation [C]:
```javascript
const file = new DB_BufferFile(some_db_uri);
TextBuffer.load(file).then(function(buffer){
      options.buffer = buffer;
      atom.workspace.open(path, options)
```
 - which has one drawback: the actual -new TextEditor(options)- call, the Atom Workspace / the Opener does, would require also the buffer parameter, which seems explicitly inhibited for default workspace.open() usage (and therefore not the way to go?):
https://github.com/atom/atom/blob/master/src/workspace.js#L1166
actually, two drawbacks:
https://github.com/atom/atom/blob/master/src/text-editor.js#L196
Leaving the default initialization of the TextBuffer in TextEditor seems like a good thing, as it reduces things for me to worry about, should more TextBuffer<->TextEditor entanglements occour, like the LanguageMode.

Thats why I'd rather use the [A]/[A*] approach - to have more reliability regarding 'stable & usable api'.

Launching an empty TextEditor,
setFile( customFileObject ) with some kind of explicit reload() on TextEditor's fresh Buffer,
feels like the most solid approach to me.

How do you see it / worth fixing - or am i twisting the actual TextBuffer.setFile meaning to much here, to rely on it to be the 'backbone of this usecase', as outlined in [A*]?

best regards
ludwig

___
DB_BufferedFile (./file_wrapper.js):
```
const stream = require('stream');

class WritableStream extends stream.Writable {
  constructor(options) {
    super(options)
    this.data = ''
  }

  _write(chunk, encoding, callback) {
    this.data += chunk;
    callback();
  }


  _final(callback) {
    atom.notifications.addError("saving file not implemented")
    callback();
  }
}

class ReadableStream extends stream.Readable {
  constructor(options) {
    super(options);
  }

  _read() {
    this.push('content')
    this.push(null);
  }
}

class DB_BufferedFile {
  constructor (path) {
    this.path = path;
  }

  getPath(){
    return this.path
  }

  createReadStream(options) {
    return new ReadableStream(options)
  }

  createWriteStream(options) {
    return new WritableStream(options)
  }

  existsSync() {
    return true
  }
}
```

Package Code:
```

import { CompositeDisposable } from 'atom';
import { DB_BufferedFile } from './file-wrapper';
import { TextEditor, TextBuffer } from 'atom';

export default {
  subscriptions: null,

  activate(state) {
    // Events subscribed to in atom's system can be easily cleaned up with a CompositeDisposable
    this.subscriptions = new CompositeDisposable(
      atom.workspace.addOpener((uri, options) => {
          if (uri === 'atom://test-package/test.js') {
            return new TextEditor(options);
          }
        })
    );

    // Register command that toggles this view
    this.subscriptions.add(atom.commands.add('atom-workspace', {
      'test-package:toggle': () => this.toggle()
    }));
  },

  deactivate() {
    this.subscriptions.dispose();
  },

  serialize() {
    return {};
  },

  toggle() {
    this.open('atom://test-package/test.js', {})
  },

  open(some_db_uri, options) {
    const file = new DB_BufferedFile(some_db_uri);
    atom.workspace.open(some_db_uri, options).then(item => {
      const buffer = item.getBuffer();
      const changeEvent = {
        oldText: buffer.getText(),
        oldRange: buffer.getRange()
      };

      buffer.setFile(file);
      buffer.reload().then(() =>  {
        changeEvent.newText = buffer.getText();
        changeEvent.newRange = buffer.getRange();
        buffer.emitDidChangeEvent(changeEvent)
      })
    }).catch(e => {
      console.error(e)
    })
  }
};
```

**Comment by rsese** [comment]
Sorry for the delay @ludwigkraatz - I'm not an engineer but chatted with another maintainer so wanted to share what I learned (at a high level); basically, workspace.open is really expecting to open a local file on disk.  If that's the case, Atom should be able to handle the rest.  

In your case, it looks like you have custom code because you want to work with data from a database - but since it's not just a plain file, it's expected that you would need to use custom code rather than relying directly on text-buffer.

I might not have explained things super well but if you want to talk more about your code the best place to go for help is the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638) or the [official message board](https://discuss.atom.io/).  We'll close for now since it's not clear that this is a problem with text-buffer but can always reopen or create a new issue if there's a confirmed problem.

**Comment by ludwigkraatz** [comment]
hey robert, thanks for replying.

sadly this does not really feel to be an answer that actually deals with my problem.

I'm trying to describe it another way.

When trying to use a custom File-Object, i have an issue with the launch process of the editor.

There is exactly One place, that seems actually designed for that case:
-textBuffer.setFile-

Unfortunatly it is still experimental and therefore not handling changes of file-objects belonging to that buffer (over the lifetime of the owning Editor window) very well.

Usecase 1:
Local File that is encrypted.
Will be loaded like every local file using atoms workspace.open() and then tracked by some helper identifying that it is actually an encrypted file. So it relocates the textBuffers File-Object to an encryption-aware one - but the "rerendering" of that action has to be triggered in a hacky way.

Usecase 2:
the one where the file object is entirely non-local, described in the initial issue message (same issue in regard to the rerendering).


The point is - yes i use a custom file - but code is ment to be reusable. And from my dive into the atom+textBuffer repository, the best way to allow for custom code -like the usecases described above- to be integrated into atom, seems to be the textBuffer. It even has this -experimental- notice explaining that this is exactly what the setFile method should be dealing with - at least once it is not experimental/beta anymore and more stable for other usecases than the init of the textBuffer itself..

I'm simply lobbying for that to be considered - tweak up that textBuffer.setFile(), to handle reload appropriatly - which will widen the usecases in which to use the builtin atom modules - as well as provide a stable and therefore more robust framework on which to code customized functionality - for atom.
I hope you can help me with that - by identifying engineers within your team and bring this to their attention so they can evaluate this - rather than explaining me why i supposedly should just code everything myself (which from my perspectice would be the conclusion so far; including a different workspace...).
Currently i just have not the time on my hands / mind to create accounts for different message boards - or sending mails to get invites to be in some other communication channel.. I'm just trying to help you guys to fix an issue i identified in your code - and was trying to solve that together with people who actually understand the best way how to incorporate this into the current atom-codebase..

I sincerely hope this does not read like an offensive attack/reply. I'm rather disappointed of not being understood and taken seriously in that matter.

If it is not possible to handle this (kind of issue) via github, I'm affraid my work on/with atom will be very limited - as this is the way im willing to participate when it comes to the quest of improving/dealing with openSource software.

best regards,
ludwig

ps: i really like what atom has to offer so far - so honestly i'm hoping we get this github-issue communication to work - as i'd like to participate in regards to the actual code and mid-/longterm by enriching the atom-ecosphere.



Von meinem iPhone gesendet

**Comment by lee-dohm** [comment]
There are two scenarios that `atom.workspace.open` is currently designed to handle:

1. `atom.workspace.open('filename.txt')` -- Open a file that exists on disk, which instantiates a `TextEditor` object backed by a `TextBuffer`
2. `atom.workspace.open('scheme://some-path')` -- Find the opener that matches and was previously registered via [`addOpener`](https://atom.io/docs/api/latest/Workspace#instance-addOpener), which instantiates its own view and model (for an example, see the implementation in [markdown-preview](https://github.com/atom/markdown-preview/blob/0eac72971114ef19f126c09cc726d0a907437a65/lib/main.js#L76-L93))

It sounds like what you're describing is a hybrid of the two, where you want to open something that doesn't exist on disk but you want the standard `TextEditor`/`TextBuffer` objects to handle everything other than the data layer. If you want something like that to happen, then you'll have to register an opener and create the `TextEditor`, `TextBuffer` (backed by the custom `File` object), and whatever else you need by hand.

I hope that helps and let me know if I misunderstood anything.

**Comment by ludwigkraatz** [comment]
thanks for your reply!

well, you seem to focus a lot on workspace.open, so i'm trying to explain the issue from up there:

i want to call workspace.open(uri, {file: customFile})

as this would allow me to reduce my code on whats actually custom to my usecase. And as described in the other usecase: this also applies to local text files. The only thing thats different, is that i need a custom file object - that might do de/encrypt, juggling with a db instead/additionally to the local file, or yes, even skipping local file handling at all.

as from my dive into the atom
code, this (file option) is not implemented currently.

so clearly this is quite the change for a very public api - as this might have consequences for how the registered openers would have to react on a present file option. thats why i disregarded that option entirely and tried to focus on what i can do with textbuffer/editor after the openers did their work.
that this file-patching code could lie within an custom opener, triggered by uri-sheme:// - sure.

but this is a detail, that so far wasnt pressing - as the actual issue is getting my custom
file into a buffer:

- i have to either deal with stuff i dont want/should not have to deal with, like TextBuffers LanguageMode or in general the whole initialization of it - which seems quite entangled to the textEditor. and anyways - its not like there is an workspace.open(uri, {buffer}) option - which would still have the same problematic implecations on registered openers

- so i have to sneak the empty buffer after it was created by the editor and try to patch it with a custom/new file object - which leads to the described issue: if i change the foundation of the textBuffer - its file - it does not emit any kind of reload event upwards to the editor and due to a lack of available method (as far as i could see) i have to dirty-hack one.

so from workspace.open (which is an inconvinience in API [to me] rather than an actual issue) -> i hacked my way down to textBuffer.setFile - which [to me] is an actual issue - as it blindly accepts me resetting the file without taking any action in regard to the implecation on the changed content. Although it is clearly ment to handle custom files - event thought marked as experimentL.

so either the experimental api textBuffer.setFile should shout at me "stop doing that, i already have a file - you cant simply change that!" or at least give me a way to simply trigger a changedContent event of some kind - because of that "re-setting of its file"

currently, it simply emits a "changed path" which is a usecase i understand - but its based on the assumption that when the buffer got initialized with a file, it already had the correct content - which might be the default case. but as 

1. the textBuffer already is ment to emit content changes

2. there is no 'simple' way for me to pass a custom file down to the buffer, from up at workspace.open, 

3. and in case of encryption, where the need for an actual different-than-default file object might get obvious just after the default file could read the content and some code decide, it was in need of a custom encryption-wrapping file obejct,

the addition of a changed-content functionality to the setFile method seems quite the best solution -to me-


i hope you understand my issue and aggree.

if you, besides that, have other remarks on how to handle my custom File with workspace.open, in a cleaner way than mine - im defentily open for those as well.

thanks very much for your help!
