### ISSUE TITLE
2ae952a breaks ES5 compatibility

### ISSUE THREAD

**Issue by dbkaplun** [atom/text-buffer#61]
2ae952a breaks ES5 compatibility, using ES6's `Set`. This is because of upstream atom/event-kit@84e8d17c which adds no extra functionality and can be easily reverted.

Related: slap-editor/slap#160.

**Comment by maxbrunsfeld** [comment]
Yep. Text-buffer requires a version of V8 that includes the full `Set` API.

**Comment by dbkaplun** [comment]
That makes sense. However there are programs that depend on text-buffer other than Atom. Please consider reverting that commit (which doesn't add anything) so that consumers of text-buffer don't have to support ES6.

**Comment by maxbrunsfeld** [comment]
Using the `Set` in `event-kit` is important for performance. You should upgrade to node v0.12.

**Comment by dbkaplun** [comment]
In that case, is it possible to bundle a `Set` polyfill with atom/event-kit, like [this ES6 Set implementation](https://github.com/medikoo/es6-set)? I am running v0.12 but I cannot expect the thousand or so users of [slap-editor/slap](https://github.com/slap-editor/slap) to do the same.

**Comment by maxbrunsfeld** [comment]
I would say you should do that in `slap-editor`. `Set` is a global and can be assigned at any point. It doesn't have to be done within `event-kit`.

**Comment by maxbrunsfeld** [comment]
By the way, nice work on `slap-editor`. I was unaware that `text-buffer` was being used outside of Atom.

**Comment by mnquintana** [comment]
@dbkaplun If you're going to use the latest text-buffer, why not release a new version with an updated `engines` field in `package.json` for `^0.12.0`? That way it'll only apply if your users have node ^0.12.0.
