### ISSUE TITLE
The text cursor doesn't display when it's on the 80 column line.

### ISSUE THREAD

**Issue by AustP** [atom/text-buffer#78]
![recorded](https://cloud.githubusercontent.com/assets/2007045/8235586/05791f84-15a0-11e5-8a27-4601a6af6af5.gif)

Notice after typing `Loo` the text cursor goes away. It comes back again when I type `k`.  (v 0.210.0)

**Comment by mnquintana** [comment]
Thanks for the report! This really belongs in atom/atom though - would you mind moving it there?

**Comment by AustP** [comment]
Dang. I can't ever figure out where these issues belong. ;]

I opened the issue at https://github.com/atom/atom/issues/7331
