### ISSUE TITLE
Is it possible to convert a Point to a total byte or character offset?

### ISSUE THREAD

**Issue by jpsim** [atom/text-buffer#96]
I'm building an Atom package and need to calculate the equivalent byte offset from a given Point. How would you recommend I do this?

e.g.

```
1234
56
```

For `Point(row: 1, column: 2)` (point immediately after `6`), the equivalent byte offset would be 7.

**Comment by lee-dohm** [comment]
It looks like [`TextBuffer.characterIndexForPosition`](https://atom.io/docs/api/latest/TextBuffer#instance-characterIndexForPosition) does what you need. I assume that you'll need to supply it a Point in buffer coordinates though. If all you have is screen coordinates, you should be able to convert to buffer coordinates by using [`TextEditor.bufferPositionForScreenPosition`](https://atom.io/docs/api/latest/TextEditor#instance-bufferPositionForScreenPosition).

**Comment by jpsim** [comment]
Thanks, that's exactly what I needed.

**Comment by lee-dohm** [comment]
You're welcome :grinning:
